#!/bin/bash

warning_days=$(chage -l $USER | grep "Number of days" | sed 's/Number of days of warning before password expires[[:space:]]*:[[:space:]]*//')

last_change_day=$(chage -l $USER | grep "Last password change" | sed 's/Last password change[[:space:]]*:[[:space:]]*//' | awk {'print $2'} | cut -d ',' -f 1)
last_change_day=$(echo $last_change_day | sed 's/^0//')

last_change_month=$(chage -l $USER | grep "Last password change" | sed 's/Last password change[[:space:]]*:[[:space:]]*//' | awk {'print $1'})

last_change_year=$(chage -l $USER | grep "Last password change" | sed 's/Last password change[[:space:]]*:[[:space:]]*//' | awk {'print $3'})

case "$last_change_month" in
  Jan)  last_change_month=1 ;;
  Feb)  last_change_month=2 ;;
  Mar)  last_change_month=3 ;;
  Apr)  last_change_month=4 ;;
  May)  last_change_month=5 ;;
  Jun)  last_change_month=6 ;;
  Jul)  last_change_month=7 ;;
  Aug)  last_change_month=8 ;;
  Sep)  last_change_month=9 ;;
  Oct)  last_change_month=10 ;;
  Nov)  last_change_month=11 ;;
  Dec)  last_change_month=12 ;;
esac

echo "WDAYS: $warning_days"
echo
echo "LCDAY: $last_change_day"
echo "LCMONTH: $last_change_month"
echo "LCYEAR: $last_change_year"
echo

cur_day=$(date +%d)
cur_month=$(date +"%-m")
cur_year=$(date +%Y)

echo "CURDAY: $cur_day"
echo "CURMONTH: $cur_month"
echo "CURYEAR: $cur_year"

last_change_days=$(($cur_year*365+$last_change_day))
